replicaCount: 2

image:
  repository: ghcr.io/ruanmcsilva/kubepod-app
  tag: "9c32f103397c5c91365491edb82ac162502bdf2e"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: "default"

service:
  port: 80
  targetPort: 8000
